name: Excavator
on:
  schedule:
    # 每天北京时间早上 8:00 自动运行
    - cron: '0 0 * * *'
  workflow_dispatch:  # 这个让你可以手动运行

jobs:
  excavate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Excavator
        uses: ScoopInstaller/Excavator@master
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: '自动更新: ${{ github.run_id }}'
          add: 'bucket/*.json'
          default_author: github_actions