name: Excavator
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      apps:
        description: '要更新的应用 (逗号分隔，留空更新所有)'
        required: false

jobs:
  excavate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Excavator
        uses: ScoopInstaller/Excavator@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update: ${{ github.run_id }}'
          add: 'bucket/*.json'
          default_author: github_actions
          push: true
